#' Create Geocodes dataset for HMISdata package
#' This script creates the Geocodes dataset containing Ohio homeless planning regions

# Load required packages
library(tibble)
library(usethis)

Geocodes <- tibble::tribble(
  ~GeographicCode, ~State,               ~Name,    ~Type,      ~County,
          390066L,   "OH",          "Alliance",   "City",      "Stark",
          390294L,   "OH",         "Barberton",   "City",     "Summit",
          390600L,   "OH",     "Bowling Green",   "City",       "Wood",
          391110L,   "OH", "Cleveland Heights",   "City",     "Summit",
          391320L,   "OH",    "Cuyahoga Falls",   "City",     "Summit",
          391500L,   "OH",    "East Cleveland",   "City",   "Cuyahoga",
          391602L,   "OH",            "Elyria",   "City",     "Lorain",
          391626L,   "OH",            "Euclid",   "City",   "Cuyahoga",
          391638L,   "OH",          "Fairborn",   "City",     "Greene",
          392118L,   "OH",     "Hamilton City",   "City",     "Butler",
          392508L,   "OH",              "Kent",   "City",    "Portage",
          392526L,   "OH",         "Kettering",   "City", "Montgomery",
          392634L,   "OH",         "Lancaster",   "City",  "Fairfield",
          392730L,   "OH",              "Lima",   "City",      "Allen",
          392820L,   "OH",            "Lorain",   "City",     "Lorain",
          393012L,   "OH",         "Mansfield",   "City",   "Richland",
          393054L,   "OH",          "Marietta",   "City", "Washington",
          393114L,   "OH",         "Massillon",   "City",      "Stark",
          393168L,   "OH",            "Mentor",   "City",       "Lake",
          393222L,   "OH",        "Middletown",   "City",     "Butler",
          393558L,   "OH",            "Newark",   "City",    "Licking",
          394098L,   "OH",             "Parma",   "City",   "Cuyahoga",
          394680L,   "OH",          "Sandusky",   "City",       "Erie",
          395016L,   "OH",      "Steubenville",   "City",  "Jefferson",
          395454L,   "OH",            "Warren",   "City",   "Trumbull",
          399001L,   "OH",      "Adams County", "County",      "Adams",
          399003L,   "OH",      "Allen County", "County",      "Allen",
          399005L,   "OH",    "Ashland County", "County",    "Ashland",
          399007L,   "OH",  "Ashtabula County", "County",  "Ashtabula",
          399009L,   "OH",     "Athens County", "County",     "Athens",
          399011L,   "OH",   "Auglaize County", "County",   "Auglaize",
          399013L,   "OH",    "Belmont County", "County",    "Belmont",
          399015L,   "OH",      "Brown County", "County",      "Brown",
          399017L,   "OH",     "Butler County", "County",     "Butler",
          399019L,   "OH",    "Carroll County", "County",    "Carroll",
          399021L,   "OH",  "Champaign County", "County",  "Champaign",
          399023L,   "OH",      "Clark County", "County",      "Clark",
          399025L,   "OH",   "Clermont County", "County",   "Clermont",
          399027L,   "OH",    "Clinton County", "County",    "Clinton",
          399031L,   "OH",  "Coshocton County", "County",  "Coshocton",
          399033L,   "OH",   "Crawford County", "County",   "Crawford",
          399037L,   "OH",      "Darke County", "County",      "Darke",
          399039L,   "OH",   "Defiance County", "County",   "Defiance",
          399041L,   "OH",   "Delaware County", "County",   "Delaware",
          399043L,   "OH",       "Erie County", "County",       "Erie",
          399045L,   "OH",  "Fairfield County", "County",  "Fairfield",
          399047L,   "OH",    "Fayette County", "County",    "Fayette",
          399051L,   "OH",     "Fulton County", "County",     "Fulton",
          399053L,   "OH",     "Gallia County", "County",     "Gallia",
          399055L,   "OH",     "Geauga County", "County",     "Geauga",
          399057L,   "OH",     "Greene County", "County",     "Greene",
          399059L,   "OH",   "Guernsey County", "County",   "Guernsey",
          399063L,   "OH",    "Hancock County", "County",    "Hancock",
          399065L,   "OH",     "Hardin County", "County",     "Hardin",
          399067L,   "OH",   "Harrison County", "County",   "Harrison",
          399069L,   "OH",      "Henry County", "County",      "Henry",
          399071L,   "OH",   "Highland County", "County",   "Highland",
          399073L,   "OH",    "Hocking County", "County",    "Hocking",
          399075L,   "OH",     "Holmes County", "County",     "Holmes",
          399077L,   "OH",      "Huron County", "County",      "Huron",
          399079L,   "OH",    "Jackson County", "County",    "Jackson",
          399081L,   "OH",  "Jefferson County", "County",  "Jefferson",
          399083L,   "OH",       "Knox County", "County",       "Knox",
          399085L,   "OH",       "Lake County", "County",       "Lake",
          399087L,   "OH",   "Lawrence County", "County",   "Lawrence",
          399089L,   "OH",    "Licking County", "County",    "Licking",
          399091L,   "OH",      "Logan County", "County",      "Logan",
          399093L,   "OH",     "Lorain County", "County",     "Lorain",
          399095L,   "OH",      "Lucas County", "County",      "Lucas",
          399097L,   "OH",    "Madison County", "County",    "Madison",
          399099L,   "OH",   "Mahoning County", "County",   "Mahoning",
          399101L,   "OH",     "Marion County", "County",     "Marion",
          399103L,   "OH",     "Medina County", "County",     "Medina",
          399105L,   "OH",      "Meigs County", "County",      "Meigs",
          399107L,   "OH",     "Mercer County", "County",     "Mercer",
          399109L,   "OH",      "Miami County", "County",      "Miami",
          399111L,   "OH",     "Monroe County", "County",     "Monroe",
          399115L,   "OH",     "Morgan County", "County",     "Morgan",
          399117L,   "OH",     "Morrow County", "County",     "Morrow",
          399121L,   "OH",      "Noble County", "County",      "Noble",
          399123L,   "OH",     "Ottawa County", "County",     "Ottawa",
          399125L,   "OH",   "Paulding County", "County",   "Paulding",
          399127L,   "OH",      "Perry County", "County",      "Perry",
          399129L,   "OH",   "Pickaway County", "County",   "Pickaway",
          399131L,   "OH",       "Pike County", "County",       "Pike",
          399133L,   "OH",    "Portage County", "County",    "Portage",
          399135L,   "OH",     "Preble County", "County",     "Preble",
          399137L,   "OH",     "Putnam County", "County",     "Putnam",
          399139L,   "OH",   "Richland County", "County",   "Richland",
          399141L,   "OH",       "Ross County", "County",       "Ross",
          399143L,   "OH",   "Sandusky County", "County",   "Sandusky",
          399145L,   "OH",     "Scioto County", "County",     "Scioto",
          399147L,   "OH",     "Seneca County", "County",     "Seneca",
          399149L,   "OH",     "Shelby County", "County",     "Shelby",
          399151L,   "OH",      "Stark County", "County",      "Stark",
          399153L,   "OH",     "Summit County", "County",     "Summit",
          399155L,   "OH",   "Trumbull County", "County",   "Trumbull",
          399157L,   "OH", "Tuscarawas County", "County", "Tuscarawas",
          399159L,   "OH",      "Union County", "County",      "Union",
          399161L,   "OH",   "Van Wert County", "County",   "Van Wert",
          399163L,   "OH",     "Vinton County", "County",     "Vinton",
          399165L,   "OH",     "Warren County", "County",     "Warren",
          399167L,   "OH", "Washington County", "County", "Washington",
          399169L,   "OH",      "Wayne County", "County",      "Wayne",
          399171L,   "OH",   "Williams County", "County",   "Williams",
          399173L,   "OH",       "Wood County", "County",       "Wood",
          399175L,   "OH",    "Wyandot County", "County",    "Wyandot",
          390042L,   "OH",             "Akron",   "City",     "Summit",
          390858L,   "OH",            "Canton",   "City",      "Stark",
          391062L,   "OH",        "Cincinnati",   "City",   "Hamilton",
          391104L,   "OH",         "Cleveland",   "City",   "Cuyahoga",
          391176L,   "OH",          "Columbus",   "City",      "Clark",
          391362L,   "OH",            "Dayton",   "City", "Montgomery",
          392628L,   "OH",          "Lakewood",   "City",   "Cuyahoga",
          394998L,   "OH",       "Springfield",   "City",      "Clark",
          395214L,   "OH",            "Toledo",   "City",      "Lucas",
          395874L,   "OH",        "Youngstown",   "City",   "Mahoning",
          399035L,   "OH",   "Cuyahoga County", "County",   "Cuyahoga",
          399049L,   "OH",   "Franklin County", "County",   "Franklin",
          399061L,   "OH",   "Hamilton County", "County",   "Hamilton",
          399113L,   "OH", "Montgomery County", "County", "Montgomery",
          399029L,   "OH", "Columbiana County", "County", "Columbiana",
          399119L,   "OH",  "Muskingum County", "County",  "Muskingum"
  )


usethis::use_data(Geocodes, overwrite = TRUE)
