## code to prepare `ServiceAreas` dataset goes here

# Source:


# Create  data
ServiceAreas <- tibble::tribble(
  ~ssvf_service_area, ~county,
  "Lutheran Social Services", "Adams",
  "St. Vincent DePaul", "Allen",
  "Salvation Army", "Ashland",
  "FrontLine Services", "Ashtabula",
  "WM CAP", "Athens",
  "St. Vincent DePaul", "Auglaize",
  "WM CAP", "Belmont",
  "Lutheran Social Services", "Brown",
  "Talbert House", "Butler",
  "Columbiana CAA", "Carroll",
  "St. Vincent DePaul", "Champaign",
  "St. Vincent DePaul", "Clark",
  "Talbert House", "Clermont",
  "St. Vincent DePaul", "Clinton",
  "Columbiana CAA", "Columbiana",
  "Licking County Coalition for Housing", "Coshocton",
  "Salvation Army", "Crawford",
  NA, "Cuyahoga",
  "St. Vincent DePaul", "Darke",
  "Maumee Valley Guidance Center", "Defiance",
  "Salvation Army", "Delaware",
  "Great Lakes Community Action Partnership", "Erie ",
  "Lutheran Social Services", "Fairfield ",
  "Lutheran Social Services", "Fayette",
  NA, "Franklin",
  "Maumee Valley Guidance Center", "Fulton",
  "WM CAP", "Gallia",
  "Family and Community Services", "Geauga",
  "St. Vincent DePaul", "Greene",
  "WM CAP", "Guernsey",
  NA, "Hamilton",
  "Great Lakes Community Action Partnership", "Hancock",
  "Salvation Army", "Hardin",
  "Columbiana CAA", "Harrison",
  "Maumee Valley Guidance Center", "Henry",
  "Lutheran Social Services", "Highland",
  "Lutheran Social Services", "Hocking",
  "Licking County Coalition for Housing", "Holmes",
  "Great Lakes Community Action Partnership", "Huron",
  "WM CAP", "Jackson",
  "Columbiana CAA", "Jefferson",
  "Licking County Coalition for Housing", "Knox",
  "FrontLine Services", "Lake",
  "WM CAP", "Lawrence",
  "Licking County Coalition for Housing", "Licking",
  "Salvation Army", "Logan",
  "Family and Community Services", "Lorain",
  NA, "Lucas",
  "Salvation Army", "Madison",
  "Family and Community Services", "Mahoning",
  "Salvation Army", "Marion",
  "Family and Community Services", "Medina",
  "WM CAP", "Meigs",
  "St. Vincent DePaul", "Mercer",
  "St. Vincent DePaul", "Miami",
  "WM CAP", "Monroe",
  NA, "Montgomery",
  "WM CAP", "Morgan",
  "Salvation Army", "Morrow",
  "WM CAP", "Muskingum",
  "WM CAP", "Noble",
  "Great Lakes Community Action Partnership", "Ottawa",
  "Maumee Valley Guidance Center", "Paulding",
  "Lutheran Social Services", "Perry",
  "Lutheran Social Services", "Pickaway",
  "WM CAP", "Pike",
  "Family and Community Services", "Portage",
  "St. Vincent DePaul", "Preble",
  "Maumee Valley Guidance Center", "Putnam",
  "Salvation Army", "Richland",
  "Lutheran Social Services", "Ross",
  "Great Lakes Community Action Partnership", "Sandusky",
  "WM CAP", "Scioto",
  "Great Lakes Community Action Partnership", "Seneca",
  "St. Vincent DePaul", "Shelby",
  NA, "Stark",
  NA, "Summit",
  "Family and Community Services", "Trumbull",
  "Columbiana CAA", "Tuscarawas",
  "Salvation Army", "Union",
  "Maumee Valley Guidance Center", "Van Wert",
  "WM CAP", "Vinton",
  "Talbert House", "Warren",
  "WM CAP", "Washington",
  "Salvation Army", "Wayne",
  "Maumee Valley Guidance Center", "Williams",
  "Great Lakes Community Action Partnership", "Wood",
  "Great Lakes Community Action Partnership", "Wyandot"
)

usethis::use_data(ServiceAreas, overwrite = TRUE)

